POST http://localhost:5050/v1.0/bindings/twilio HTTP/1.1
content-type: application/json

{
    "data": "cookies ready from Dapr",
    "metadata": {
        "toNumber": "# Replace"
    },
    "operation": "create"
}