POST http://localhost:5001/order HTTP/1.1
content-type: application/json

{
  "CustomerCode": "Davide",
  "Date": "2020-09-19T08:47:53.1224585Z",
  "Items": [
    {
      "ProductCode": "rockiecookie",
      "Quantity": 4
    },
    {
      "ProductCode": "bussola9",
      "Quantity": 7
    },
    {
      "ProductCode": "bussola1",
      "Quantity": 2
    },
    {
      "ProductCode": "crazycookie",
      "Quantity": 2
    }
  ],
  "SpecialRequests" : [
    {
      "CustomizationId" : "08ffffcc-7591-4702-ffff-fff6787bfffe",
      "Scope": 
      {
        "ProductCode": "crazycookie",
        "Quantity": 1
      }
    },
    {
      "CustomizationId" : "08ffffcc-7591-4702-ffff-fff6787bfffe",
      "Scope": 
      {
        "ProductCode": "rockiecookie",
        "Quantity": 2
      }
    }
  ]
}
###
GET http://localhost:5001/order/08ec11cc-7591-4702-bb4d-7e86787b64fe
###
GET http://localhost:5010/v1.0/state/orderstore/08ec11cc-7591-4702-bb4d-7e86787b64fe
###
GET http://localhost:5002/balance/rockiecookie HTTP/1.1