POST http://localhost:5001/order HTTP/1.1
content-type: application/json

{
  "CustomerCode": "Davide",
  "Date": "2020-09-19T08:47:53.1224585Z",
  "Items": [
    {
      "ProductCode": "rockiecookie",
      "Quantity": 4
    },
    {
      "ProductCode": "bussola8",
      "Quantity": 7
    },
    {
      "ProductCode": "crazycookie",
      "Quantity": 2
    }
  ],
  "SpecialRequests" : [
    {
      "CustomizationId" : "08ffffcc-7591-4702-ffff-fff6787bfffe",
      "Scope": 
      {
        "ProductCode": "crazycookie",
        "Quantity": 1
      }
    },
    {
      "CustomizationId" : "08ffffcc-7591-4702-ffff-fff6787bfffe",
      "Scope": 
      {
        "ProductCode": "rockiecookie",
        "Quantity": 2
      }
    }
  ]
}
###
GET http://localhost:5001/order/08ec11cc-7591-4702-bb4d-7e86787b64fe
###
GET http://localhost:5010/v1.0/state/orderstore/08ec11cc-7591-4702-bb4d-7e86787b64fe
###
POST http://localhost:5002/reserve HTTP/1.1
content-type: application/json

{
    "SKU": "cookie2",
    "Quantity": 4
}
###
GET http://localhost:5020/v1.0/state/reservationstore/cookie2  HTTP/1.1
###
GET http://localhost:5002/balance/cookie43 HTTP/1.1
###
POST http://localhost:5020/v1.0/state/reservationitemstore HTTP/1.1
content-type: application/json

[
  {
    "key": "cookie43",
    "value": {
        "SKU": "cookie43",
        "BalanceQuantity": 65,
      "Changes": []
      }
  },
  {
    "key": "bussola8",
    "value": {
        "SKU": "bussola8",
        "BalanceQuantity": 8,
      "Changes": []
      }
  },
  {
    "key": "rockiecookie",
    "value": {
        "SKU": "rockiecookie",
        "BalanceQuantity": 80,
      "Changes": []
      }
  },
  {
    "key": "crazycookie",
    "value": {
        "SKU": "crazycookie",
        "BalanceQuantity": 23,
      "Changes": []
      }
  }
]

